//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 01:33:12 AM TRT 
//


package com.example.stilus.ws.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="computeResponse" type="{http://localhost:8080/stilus/stilus-compute-web-service}computeResponse"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "computeResponse"
})
@XmlRootElement(name = "getComputeResponse")
public class GetComputeResponse {

    @XmlElement(required = true)
    protected ComputeResponse computeResponse;

    /**
     * Gets the value of the computeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ComputeResponse }
     *     
     */
    public ComputeResponse getComputeResponse() {
        return computeResponse;
    }

    /**
     * Sets the value of the computeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComputeResponse }
     *     
     */
    public void setComputeResponse(ComputeResponse value) {
        this.computeResponse = value;
    }

}
