//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 01:33:12 AM TRT 
//


package com.example.stilus.ws.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ilkDeger" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="ikinciDeger" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="islem" type="{http://localhost:8080/stilus/stilus-compute-web-service}islem"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ilkDeger",
    "ikinciDeger",
    "islem"
})
@XmlRootElement(name = "getComputeRequest")
public class GetComputeRequest {

    protected float ilkDeger;
    protected float ikinciDeger;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Islem islem;

    /**
     * Gets the value of the ilkDeger property.
     * 
     */
    public float getIlkDeger() {
        return ilkDeger;
    }

    /**
     * Sets the value of the ilkDeger property.
     * 
     */
    public void setIlkDeger(float value) {
        this.ilkDeger = value;
    }

    /**
     * Gets the value of the ikinciDeger property.
     * 
     */
    public float getIkinciDeger() {
        return ikinciDeger;
    }

    /**
     * Sets the value of the ikinciDeger property.
     * 
     */
    public void setIkinciDeger(float value) {
        this.ikinciDeger = value;
    }

    /**
     * Gets the value of the islem property.
     * 
     * @return
     *     possible object is
     *     {@link Islem }
     *     
     */
    public Islem getIslem() {
        return islem;
    }

    /**
     * Sets the value of the islem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Islem }
     *     
     */
    public void setIslem(Islem value) {
        this.islem = value;
    }

}
