//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 01:33:12 AM TRT 
//


package com.example.stilus.ws.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for islem.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="islem"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="toplama"/&gt;
 *     &lt;enumeration value="cikarma"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "islem")
@XmlEnum
public enum Islem {

    @XmlEnumValue("toplama")
    TOPLAMA("toplama"),
    @XmlEnumValue("cikarma")
    CIKARMA("cikarma");
    private final String value;

    Islem(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Islem fromValue(String v) {
        for (Islem c: Islem.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
